### ISSUE TITLE
gifs not working

### ISSUE THREAD

**Issue by AE-GM** [AlexPresso/Spoilar-bd-plugin#1]
it's not marking the gifs (embeds) as spoilers

**Comment by AlexPresso** [comment]
Yes it's not manipulating embed fiels, I can add it when I have time

**Comment by AlexPresso** [comment]
Wait no, it's supposed to completly remove embeds if you enable the setting 

Could you send a screenshot of your settings please

**Comment by AE-GM** [comment]
thanks for the quick respond 
but the settings only  shows the setting for user id

**Comment by AE-GM** [comment]
![image](https://user-images.githubusercontent.com/72312570/194024841-20d1fb06-a28b-408e-b30a-752afcf16a58.png)
the reason it is not showing could be a cause of xenolib
2nd edit: maybe not, it wasn't showing signs of xenolib

**Comment by AlexPresso** [comment]
It's strange but it seems you're not using the latest version, you're supposed to have three switch buttons to enable different types of spoils

**Comment by AlexPresso** [comment]
I just noticed the download link from the repository homepage was outdated. Fixed it.
Please download the latest version from the release page: https://github.com/AlexPresso/Spoilar-bd-plugin/releases 

Let me know if the problem is solved.

**Comment by AlexPresso** [comment]
Feel free to reopen the issue if your problem is not solved.
